
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pidautoscaler-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pidautoscaler-simulator
  template:
    metadata:
      labels:
        app: pidautoscaler-simulator
    spec:
      containers:
      - name: simulator
        image: pidautoscaler-simulator:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: pidautoscaler-simulator-service
spec:
  selector:
    app: pidautoscaler-simulator
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
